# Generated by Django 5.0 on 2023-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='type',
            field=models.ManyToManyField(blank=True, to='tbot.typenotes'),
        ),
    ]
